public enum EventID
{
    EVENT_GAME_STATE_CHANGED,
    EVENT_DIRECTION_DECIDED,
    EVENT_FORCE_DECIDED,
    EVENT_BALL_OUT_OF_PLAY,
    EVENT_TURN_END,
    EVENT_MATCH_END,
    EVENT_SCORE_UPDATED
}
